### ISSUE TITLE
Error: uninitialized constant Hamlit::StaticAnalyzer (NameError)

### ISSUE THREAD

**Issue by zavan** [hamlit/hamlit-block#4]
Hi, thanks for the gem! I'm trying to use it with rails and cells-hamlit, but I'm getting an error:
```
/home/zavan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/hamlit-block-0.5.0/lib/hamlit/block/engine.rb:24:in `<class:Engine>': uninitialized constant Hamlit::StaticAnalyzer (NameError)
	from /home/zavan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/hamlit-block-0.5.0/lib/hamlit/block/engine.rb:6:in `<module:Block>'
	from /home/zavan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/hamlit-block-0.5.0/lib/hamlit/block/engine.rb:5:in `<module:Hamlit>'
	from /home/zavan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/hamlit-block-0.5.0/lib/hamlit/block/engine.rb:4:in `<top (required)>'
	from /home/zavan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/hamlit-block-0.5.0/lib/hamlit/block.rb:2:in `<top (required)>'
	from /home/zavan/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:105:in `require'
        ...
```

Relevant gem versions:
```
cells (4.1.6)
cells-hamlit (0.2.0)
cells-rails (0.0.7)
hamlit (2.8.0)
hamlit-block (0.5.0)
hamlit-rails (0.2.0)
rails (5.0.1)
```

My cell:
```ruby
module ALM
  class Cell < Trailblazer::Cell
    include ActionView::Helpers::TranslationHelper
    include SimpleForm::ActionViewExtensions::FormHelper
    include ::Cell::Hamlit
    include ::Cell::Translation
  end
end
```

I tried searching for `Hamlit::StaticAnalyzer` inside the hamlit gem but couldn't find it.

**Comment by k0kubun** [comment]
Oops, sorry. Fixed it in v0.6.0. Could you try it?

**Comment by k0kubun** [comment]
Apart from that error, hamlit-block >= 0.4.0 won't work with cells-hamlit <= 0.2.0. So I suggest you to use hamlit v2.8.0 and cells-hamlit v0.1.0 for now. cells-hamlit v0.1.0 doesn't require hamlit-block.

To use cells-hamlit with hamlit-block, we should wait https://github.com/trailblazer/cells-hamlit/issues/6 to be closed.

**Comment by zavan** [comment]
I'll wait.
Thank you!
